name: Bug Report
description: Report issues with the Maester Github Action here.
title: "[BUG] "
labels: [bug]
body:
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: action_version
  attributes:
    label: What version of the action are you using?
    description: Please provide the version of the action you are using.
    placeholder: v1.0.0 / main / ..
  validations:
    required: true
- type: input
  id: maester_version
  attributes:
    label: What version of Maester are you using?
    description: "Please provide the version of Maester you are using, it is in the logs as: Installed Maester version: 1.0.83"
    placeholder: 1.0.0 / 1.0.83
  validations:
    required: true
- type: input
  id: public_tests_version
  attributes:
    label: What version of public tests are you using?
    description: It is possible to use a different git reference for the public tests. Which one are you using?
    placeholder: main
- type: textarea
  id: issue_description
  attributes:
    label: Describe the bug
    description: Please provide a clear and concise description of the bug you encountered.
    placeholder: A clear and concise description of the bug.
  validations:
    required: true
